/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DiseaseCertificateService } from "../diseaseCertificate.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DiseaseCertificateCreateInput } from "./DiseaseCertificateCreateInput";
import { DiseaseCertificate } from "./DiseaseCertificate";
import { DiseaseCertificateFindManyArgs } from "./DiseaseCertificateFindManyArgs";
import { DiseaseCertificateWhereUniqueInput } from "./DiseaseCertificateWhereUniqueInput";
import { DiseaseCertificateUpdateInput } from "./DiseaseCertificateUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DiseaseCertificateControllerBase {
  constructor(
    protected readonly service: DiseaseCertificateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DiseaseCertificate })
  @nestAccessControl.UseRoles({
    resource: "DiseaseCertificate",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDiseaseCertificate(
    @common.Body() data: DiseaseCertificateCreateInput
  ): Promise<DiseaseCertificate> {
    return await this.service.createDiseaseCertificate({
      data: {
        ...data,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        expiryDate: true,
        file: true,
        issueDate: true,

        employee: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DiseaseCertificate] })
  @ApiNestedQuery(DiseaseCertificateFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DiseaseCertificate",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async diseaseCertificates(
    @common.Req() request: Request
  ): Promise<DiseaseCertificate[]> {
    const args = plainToClass(DiseaseCertificateFindManyArgs, request.query);
    return this.service.diseaseCertificates({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        expiryDate: true,
        file: true,
        issueDate: true,

        employee: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DiseaseCertificate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiseaseCertificate",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async diseaseCertificate(
    @common.Param() params: DiseaseCertificateWhereUniqueInput
  ): Promise<DiseaseCertificate | null> {
    const result = await this.service.diseaseCertificate({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        expiryDate: true,
        file: true,
        issueDate: true,

        employee: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DiseaseCertificate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiseaseCertificate",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDiseaseCertificate(
    @common.Param() params: DiseaseCertificateWhereUniqueInput,
    @common.Body() data: DiseaseCertificateUpdateInput
  ): Promise<DiseaseCertificate | null> {
    try {
      return await this.service.updateDiseaseCertificate({
        where: params,
        data: {
          ...data,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          expiryDate: true,
          file: true,
          issueDate: true,

          employee: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DiseaseCertificate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiseaseCertificate",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDiseaseCertificate(
    @common.Param() params: DiseaseCertificateWhereUniqueInput
  ): Promise<DiseaseCertificate | null> {
    try {
      return await this.service.deleteDiseaseCertificate({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          expiryDate: true,
          file: true,
          issueDate: true,

          employee: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
