/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PresenceService } from "../presence.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PresenceCreateInput } from "./PresenceCreateInput";
import { Presence } from "./Presence";
import { PresenceFindManyArgs } from "./PresenceFindManyArgs";
import { PresenceWhereUniqueInput } from "./PresenceWhereUniqueInput";
import { PresenceUpdateInput } from "./PresenceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PresenceControllerBase {
  constructor(
    protected readonly service: PresenceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Presence })
  @nestAccessControl.UseRoles({
    resource: "Presence",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPresence(
    @common.Body() data: PresenceCreateInput
  ): Promise<Presence> {
    return await this.service.createPresence({
      data: {
        ...data,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dateTimeOfPresence: true,
        status: true,
        hours: true,

        employee: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Presence] })
  @ApiNestedQuery(PresenceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Presence",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async presences(@common.Req() request: Request): Promise<Presence[]> {
    const args = plainToClass(PresenceFindManyArgs, request.query);
    return this.service.presences({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dateTimeOfPresence: true,
        status: true,
        hours: true,

        employee: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Presence })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Presence",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async presence(
    @common.Param() params: PresenceWhereUniqueInput
  ): Promise<Presence | null> {
    const result = await this.service.presence({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dateTimeOfPresence: true,
        status: true,
        hours: true,

        employee: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Presence })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Presence",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePresence(
    @common.Param() params: PresenceWhereUniqueInput,
    @common.Body() data: PresenceUpdateInput
  ): Promise<Presence | null> {
    try {
      return await this.service.updatePresence({
        where: params,
        data: {
          ...data,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          dateTimeOfPresence: true,
          status: true,
          hours: true,

          employee: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Presence })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Presence",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePresence(
    @common.Param() params: PresenceWhereUniqueInput
  ): Promise<Presence | null> {
    try {
      return await this.service.deletePresence({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          dateTimeOfPresence: true,
          status: true,
          hours: true,

          employee: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
